name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}
      run: echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin

    - name: Build the Client Docker image
      run: docker build . --file Client/Dockerfile --tag mwajoe/me:extrasize_client

    - name: Build the Server Docker image
      run: docker build . --file Server/Dockerfile --tag mwajoe/me:extrasize_server

    - name: Push Client to Dockerhub
      run: docker push mwajoe/me:extrasize_client

    - name: Push Server to Dockerhub
      run: docker push mwajoe/me:extrasize_server
